#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WeatherApp1.Resource", IsApplication=true)]

namespace WeatherApp1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040010
			public const int HumidityText = 2130968592;
			
			// aapt resource value: 0x7f040005
			public const int ResultsTable = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int ResultsTitle = 2130968580;
			
			// aapt resource value: 0x7f040018
			public const int SunriseText = 2130968600;
			
			// aapt resource value: 0x7f04001b
			public const int SunsetText = 2130968603;
			
			// aapt resource value: 0x7f040008
			public const int TempText = 2130968584;
			
			// aapt resource value: 0x7f040014
			public const int VisibilityText = 2130968596;
			
			// aapt resource value: 0x7f04000c
			public const int WindText = 2130968588;
			
			// aapt resource value: 0x7f040001
			public const int ZipCodeLabel = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int GetWeatherButton = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int ZipCodeEdit = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int relativeLayout1 = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int tableRow1 = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int tableRow2 = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public const int tableRow3 = 2130968590;
			
			// aapt resource value: 0x7f040012
			public const int tableRow4 = 2130968594;
			
			// aapt resource value: 0x7f040016
			public const int tableRow5 = 2130968598;
			
			// aapt resource value: 0x7f040019
			public const int tableRow6 = 2130968601;
			
			// aapt resource value: 0x7f040007
			public const int textView21 = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int textView22 = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int textView23 = 2130968591;
			
			// aapt resource value: 0x7f040009
			public const int textView26 = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int textView27 = 2130968589;
			
			// aapt resource value: 0x7f040011
			public const int textView28 = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int textView34 = 2130968595;
			
			// aapt resource value: 0x7f040017
			public const int textView40 = 2130968599;
			
			// aapt resource value: 0x7f04001a
			public const int textView46 = 2130968602;
			
			// aapt resource value: 0x7f040015
			public const int textView50 = 2130968597;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
